name: Release

on:
  push:
    branches:
    - main

jobs:
  version-check:
    name: New version?
    runs-on: ubuntu-latest

    outputs:
      is_version_greater: ${{ steps.pyproject-version.outputs.is_version_greater }}
      version: ${{ steps.pyproject-version.outputs.version }}
    steps:
    - uses: raven-wing/did-python-package-version-change@v1
      id: pyproject-version

  changelog:
    name: Parse version's changelog
    needs: version-check
    runs-on: ubuntu-latest

    outputs:
      changes: ${{ steps.changelog.outputs.description }}

    steps:
    - name: Checkout the repository
      uses: actions/checkout@main
    - name: Parse Changelog Entry
      id: changelog
      uses: coditory/changelog-parser@v1
      with:
        version: ${{ needs.version-check.outputs.version }}

  build:
    name: Build dist
    runs-on: ubuntu-latest
    
    # run only if the version has changed
    needs: version-check
    if: needs.version-check.outputs.is_version_greater == 'true'

    steps:
    - name: Checkout the repository
      uses: actions/checkout@main
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v1
      with:
        enable-cache: true
        version: "0.4.5"
    - name: Build the distribution packages
      run: uv build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

  github-release:
    name: GitHub release
    needs:
    - build
    - version-check
    - changelog
    runs-on: ubuntu-latest

    permissions:
      contents: write  # IMPORTANT: mandatory for making GitHub Releases
      id-token: write  # IMPORTANT: mandatory for sigstore

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Sign the dists with Sigstore
      uses: sigstore/gh-action-sigstore-python@v2.1.1
      with:
        inputs: >-
          ./dist/*.tar.gz
          ./dist/*.whl
  
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ needs.version-check.outputs.version }}
        body: ${{ needs.changelog.outputs.changes }}
        files: dist/**

  publish-to-testpypi:
    name: Publish to TestPyPI
    needs:
    - github-release
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/py-pcbu

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish dists to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/


  publish-to-pypi:
    name: Publish to PyPI
    needs:
    - publish-to-testpypi
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/py-pcbu

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish dists to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
