name: Release

on:
  push:
    branches:
    - main

jobs:
  check:
    name: Check if the version has changed in pyproject.toml
    runs-on: ubuntu-latest

    outputs:
      is_version_greater: ${{ steps.did-version-change.outputs.is_version_greater }}
      version: ${{ steps.did-version-change.outputs.version }}
    steps:
    - uses: raven-wing/did-python-package-version-change@v1
      id: did-version-change
      
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    
    # run only if the version has changed
    needs: check
    if: needs.check.outputs.is_version_greater == 'true'

    steps:
    - name: Checkout the repository
      uses: actions/checkout@main
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v1
      with:
        enable-cache: true
        version: "0.4.5"
    - name: Build the distribution packages
      run: uv build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

  publish-to-testpypi:
    name: Publish to TestPyPI
    needs:
    - build
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/py-pcbu

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish dists to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/

  github-release:
    name: >-
      Sign the Python distribution with Sigstore
      and upload them to GitHub Release
    needs:
    - publish-to-testpypi
    - check
    runs-on: ubuntu-latest

    permissions:
      contents: write  # IMPORTANT: mandatory for making GitHub Releases
      id-token: write  # IMPORTANT: mandatory for sigstore

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Sign the dists with Sigstore
      uses: sigstore/gh-action-sigstore-python@v2.1.1
      with:
        inputs: >-
          ./dist/*.tar.gz
          ./dist/*.whl
    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: >-
        gh release create
        '${{ needs.check.outputs.version }}'
        --repo '${{ github.repository }}'
        --notes ""
    - name: Upload artifact signatures to GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      # Upload to GitHub Release using the `gh` CLI.
      # `dist/` contains the built packages, and the
      # sigstore-produced signatures and certificates.
      run: >-
        gh release upload
        '${{ github.ref_name }}' dist/**
        --repo '${{ github.repository }}'
